import Foundation

// Converts a markdown briefing into a styled HTML document for PDF export.
// Claude outputs markdown (popover-friendly), and this exporter transforms
// it into rich HTML with tables, colored sections, and print-ready CSS.
// The user then opens the HTML in Safari and uses File > Print > Save as PDF.
enum BriefingHTMLExporter {

    // MARK: - Public API

    static func generateHTML(from result: BriefingResult, scope: BriefingScope) -> String {
        let title = scopeTitle(scope: scope, date: result.generatedAt)
        let subtitle = scopeSubtitle(date: result.generatedAt)
        let body = convertMarkdownToHTML(result.markdownContent)
        let footer = "Generated by Briefing.app • \(formatDateTime(result.generatedAt))"

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>\(escapeHTML(title))</title>
        <style>
        \(cssTemplate)
        </style>
        </head>
        <body>
        <h1>\(escapeHTML(title))</h1>
        <p class="subtitle">\(escapeHTML(subtitle))</p>
        <hr>
        \(body)
        <div class="footer">\(escapeHTML(footer))</div>
        </body>
        </html>
        """
    }

    // MARK: - Scope-Specific Titles

    private static func scopeTitle(scope: BriefingScope, date: Date) -> String {
        let fmt = DateFormatter()
        switch scope {
        case .today:
            fmt.dateFormat = "EEEE, MMMM d, yyyy"
            return "Daily Briefing — \(fmt.string(from: date))"
        case .tomorrow:
            fmt.dateFormat = "EEEE, MMMM d, yyyy"
            let tomorrow = Calendar.current.date(byAdding: .day, value: 1, to: date) ?? date
            return "Tomorrow's Briefing — \(fmt.string(from: tomorrow))"
        case .week:
            fmt.dateFormat = "MMMM d, yyyy"
            return "Your Week Ahead — Week of \(fmt.string(from: date))"
        }
    }

    private static func scopeSubtitle(date: Date) -> String {
        "Generated \(formatDateTime(date)) • Michael Ammaturo"
    }

    private static func formatDateTime(_ date: Date) -> String {
        let fmt = DateFormatter()
        fmt.dateFormat = "MMMM d, yyyy 'at' h:mm a"
        return fmt.string(from: date)
    }

    // MARK: - Markdown → HTML Conversion

    // Tracks which section type we're currently inside, driving special
    // rendering behavior (calendar bullets → table rows, colored wrappers, etc.)
    private enum SectionType {
        case bottomLine
        case calendar
        case priorities
        case waiting
        case stale
        case family
        case regular
    }

    private static func detectSectionType(from headerText: String) -> SectionType {
        let lower = headerText.lowercased()
        if lower.contains("bottom line") { return .bottomLine }
        if lower.contains("calendar") || lower.contains("schedule")
            || lower.contains("day-by-day") || lower.contains("overview") { return .calendar }
        if lower.contains("priorities") || lower.contains("priority") { return .priorities }
        if lower.contains("waiting") { return .waiting }
        if lower.contains("stale") || lower.contains("overdue") { return .stale }
        // "noosh" kept for briefings cached before the Family Calendar rename
        if lower.contains("family") || lower.contains("noosh") { return .family }
        return .regular
    }

    /// Line-by-line state machine that converts markdown into HTML with
    /// section-aware rendering. Calendar bullets become table rows,
    /// sections get colored wrappers, and the Bottom Line gets a dark box.
    private static func convertMarkdownToHTML(_ markdown: String) -> String {
        let lines = markdown.components(separatedBy: "\n")
        var html: [String] = []
        var inList = false
        var inTable = false
        var inSection = false
        var currentSection: SectionType = .regular

        // Close any open list
        func closeList() {
            if inList {
                html.append("</ul>")
                inList = false
            }
        }

        // Close any open table
        func closeTable() {
            if inTable {
                html.append("</tbody></table>")
                inTable = false
            }
        }

        // Close the current section wrapper div
        func closeSection() {
            closeList()
            closeTable()
            if inSection {
                html.append("</div>")
                inSection = false
            }
        }

        // Open a new section wrapper div with the appropriate CSS class
        func openSection(_ type: SectionType, heading: String) {
            closeSection()
            currentSection = type

            switch type {
            case .bottomLine:
                html.append("<div class=\"bottom-line\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .calendar:
                html.append("<div class=\"section-block calendar\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .priorities:
                html.append("<div class=\"section-block priorities\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .waiting:
                html.append("<div class=\"section-block waiting\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .stale:
                html.append("<div class=\"section-block stale\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .family:
                html.append("<div class=\"section-block family\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            case .regular:
                html.append("<div class=\"section-block\">")
                html.append("<h3>\(processInlineFormatting(heading))</h3>")
            }
            inSection = true
        }

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)

            // Skip the h1 title — the HTML template already provides it
            if trimmed.hasPrefix("# ") && !trimmed.hasPrefix("## ") && !trimmed.hasPrefix("### ") {
                continue
            }

            // h2 heading
            if trimmed.hasPrefix("## ") {
                closeSection()
                let text = String(trimmed.dropFirst(3))
                html.append("<h2>\(processInlineFormatting(text))</h2>")
                continue
            }

            // h3 heading — triggers section detection
            if trimmed.hasPrefix("### ") {
                let text = String(trimmed.dropFirst(4))
                let type = detectSectionType(from: text)
                openSection(type, heading: text)
                continue
            }

            // Horizontal rule
            if trimmed == "---" || trimmed == "***" || trimmed == "___" {
                closeList()
                closeTable()
                html.append("<hr>")
                continue
            }

            // Empty line — close open lists/tables
            if trimmed.isEmpty {
                closeList()
                closeTable()
                continue
            }

            // Bullet lines — behavior depends on current section
            if trimmed.hasPrefix("- ") {
                let content = String(trimmed.dropFirst(2))

                if currentSection == .calendar {
                    // In calendar sections, try to parse as a time-event row
                    if let row = parseCalendarBullet(content) {
                        if !inTable {
                            html.append("<table><tbody>")
                            inTable = true
                        }
                        html.append(row)
                        continue
                    }
                }

                // Regular bullet list
                if !inList {
                    closeTable()
                    html.append("<ul>")
                    inList = true
                }
                html.append("<li>\(processInlineFormatting(content))</li>")
                continue
            }

            // Bold-only lines in calendar sections become day subheadings
            // Pattern: **Monday, Feb 23** (entire line is bold text)
            if currentSection == .calendar,
               trimmed.hasPrefix("**") && trimmed.hasSuffix("**") {
                closeTable()
                let inner = String(trimmed.dropFirst(2).dropLast(2))
                html.append("<h4 class=\"day-subheading\">\(escapeHTML(inner))</h4>")
                // Start a new table for this day's events
                html.append("<table><tbody>")
                inTable = true
                continue
            }

            // Anything else → paragraph
            closeList()
            closeTable()
            html.append("<p>\(processInlineFormatting(trimmed))</p>")
        }

        closeSection()
        return html.joined(separator: "\n")
    }

    // MARK: - Calendar Bullet Parsing

    /// Attempts to parse a calendar bullet like "**9:30–10:30 AM:** Meet David"
    /// into an HTML table row. Returns nil if the line doesn't match the pattern.
    private static func parseCalendarBullet(_ content: String) -> String? {
        // Match: **TIME:** rest  or  **ALL DAY:** rest
        // The time portion is wrapped in bold, followed by a colon
        guard content.hasPrefix("**") else { return nil }

        // Find the closing ** after the time
        guard let closingBold = content.range(of: "**", range: content.index(content.startIndex, offsetBy: 2)..<content.endIndex) else {
            return nil
        }

        let timePart = String(content[content.index(content.startIndex, offsetBy: 2)..<closingBold.lowerBound])

        // The event description follows after the bold and optional colon/space
        var rest = String(content[closingBold.upperBound...])
        // Strip leading colon and whitespace
        if rest.hasPrefix(":") { rest = String(rest.dropFirst()) }
        rest = rest.trimmingCharacters(in: .whitespaces)

        // Determine row class based on content
        let rowClass: String
        let upperRest = rest.uppercased()
        if upperRest.contains("CONFLICT") || rest.contains("⚠️") {
            rowClass = " class=\"conflict\""
        } else if upperRest.hasPrefix("FREE") {
            rowClass = " class=\"free\""
        } else {
            rowClass = ""
        }

        return "<tr\(rowClass)><td class=\"time\">\(escapeHTML(timePart))</td><td>\(processInlineFormatting(rest))</td></tr>"
    }

    // MARK: - Inline Formatting

    /// Converts inline markdown formatting to HTML: **bold**, *italic*
    private static func processInlineFormatting(_ text: String) -> String {
        var result = escapeHTML(text)

        // Bold: **text** → <strong>text</strong>
        // Use a simple scan approach since NSRegularExpression is verbose
        result = replacePattern(in: result, opening: "**", closing: "**", tag: "strong")

        // Italic: *text* → <em>text</em> (but not inside already-processed strong tags)
        result = replacePattern(in: result, opening: "*", closing: "*", tag: "em")

        return result
    }

    /// Simple pattern replacement for matched delimiters → HTML tags.
    /// Handles nested cases by processing from left to right.
    private static func replacePattern(in text: String, opening: String, closing: String, tag: String) -> String {
        var result = ""
        var remaining = text[text.startIndex...]

        while let openRange = remaining.range(of: opening) {
            // Append everything before the opening delimiter
            result += remaining[remaining.startIndex..<openRange.lowerBound]

            let afterOpen = remaining[openRange.upperBound...]
            if let closeRange = afterOpen.range(of: closing) {
                // Found a matching close — wrap in tag
                let inner = afterOpen[afterOpen.startIndex..<closeRange.lowerBound]
                result += "<\(tag)>\(inner)</\(tag)>"
                remaining = afterOpen[closeRange.upperBound...]
            } else {
                // No matching close — keep the delimiter as-is
                result += opening
                remaining = afterOpen
            }
        }

        // Append any remaining text
        result += remaining
        return result
    }

    // MARK: - HTML Escaping

    private static func escapeHTML(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    // MARK: - CSS Template

    private static let cssTemplate = """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.5;
            color: #1D1D1F;
            max-width: 720px;
            margin: 0 auto;
            padding: 40px 20px;
        }

        h1 {
            font-size: 20pt;
            font-weight: 700;
            color: #1D1D1F;
            margin-bottom: 4px;
        }

        .subtitle {
            font-size: 9pt;
            color: #86868B;
            margin-bottom: 16px;
        }

        h2 {
            font-size: 15pt;
            font-weight: 600;
            color: #1D1D1F;
            margin-top: 24px;
            margin-bottom: 8px;
        }

        h3 {
            font-size: 12pt;
            font-weight: 600;
            margin-bottom: 8px;
        }

        h4.day-subheading {
            font-size: 11pt;
            font-weight: 600;
            color: #1D1D1F;
            margin-top: 12px;
            margin-bottom: 4px;
        }

        hr {
            border: none;
            border-top: 1px solid #D2D2D7;
            margin: 16px 0;
        }

        p {
            margin-bottom: 8px;
        }

        ul {
            margin: 4px 0 12px 20px;
        }

        li {
            margin-bottom: 4px;
        }

        /* Calendar event tables */
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 4px 0 12px 0;
            font-size: 10.5pt;
        }

        td {
            padding: 5px 8px;
            border-bottom: 1px solid #E5E5EA;
            vertical-align: top;
        }

        td.time {
            width: 130px;
            white-space: nowrap;
            font-weight: 500;
            color: #555;
        }

        tr.conflict td {
            color: #D32F2F;
            font-weight: 600;
            background-color: #FFF3F3;
        }

        tr.free td {
            color: #2E7D32;
            font-style: italic;
            background-color: #F1F8E9;
        }

        /* Section blocks with colored left borders */
        .section-block {
            background-color: #F9F9FB;
            border-left: 4px solid #D2D2D7;
            border-radius: 4px;
            padding: 12px 16px;
            margin: 12px 0;
        }

        .section-block.calendar {
            border-left-color: #007AFF;
            background-color: #F5F8FF;
        }

        .section-block.priorities {
            border-left-color: #007AFF;
            background-color: #F5F8FF;
        }

        .section-block.waiting {
            border-left-color: #FF9500;
            background-color: #FFF8F0;
        }

        .section-block.stale {
            border-left-color: #FF3B30;
            background-color: #FFF5F5;
        }

        .section-block.family {
            border-left-color: #AF52DE;
            background-color: #F9F0FF;
        }

        /* Bottom Line — dark executive summary box */
        .bottom-line {
            background-color: #2D2D2D;
            color: #E8E8ED;
            border-radius: 8px;
            padding: 16px 20px;
            margin: 12px 0;
        }

        .bottom-line h3 {
            color: #D4A843;
            font-size: 13pt;
            margin-bottom: 8px;
        }

        .bottom-line p {
            color: #E8E8ED;
            line-height: 1.6;
        }

        .bottom-line strong {
            color: #D4A843;
        }

        .bottom-line ul {
            color: #E8E8ED;
        }

        .bottom-line li {
            color: #E8E8ED;
        }

        /* Footer */
        .footer {
            margin-top: 32px;
            padding-top: 12px;
            border-top: 1px solid #D2D2D7;
            text-align: right;
            font-size: 8pt;
            color: #86868B;
        }

        /* Print styles */
        @media print {
            body {
                padding: 0;
                max-width: none;
            }

            .bottom-line,
            .section-block,
            table {
                page-break-inside: avoid;
            }

            .footer {
                page-break-before: avoid;
            }
        }

        @page {
            margin: 1in;
        }
    """
}
